version: "3"
services:
  edu_pathways:
    container_name: edu_pathways
    platform: linux/amd64
    build:
      context: ./education_pathways
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /usr/app/__pycache__
      - .:/usr/app:cached
    environment:
      - FLASK_ENV=development
    depends_on:
      - database
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/frontend/node_modules
      - .:/app:cached
    environment:
      - CHOKIDAR_USEPOLLING=true
  database:
    container_name: database
    image: postgres:14.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "4000:5432"
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "4500:8080"
