version: "3"
services:
  education_pathways:
    container_name: edu_pathways
    build:
      context: ./education_pathways
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./education_pathways:/usr/app
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
