version: "3"
services:
  education_pathways:
    container_name: edu_pathways
    build:
      context: ./education_pathways
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/app:cached
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/frontend/node_modules
      - .:/app:cached
    environment:
      - CHOKIDAR_USEPOLLING=true
  database:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "4000:5432"
  adminer:
    image: adminer
    ports:
      - "4500:8080"
